version: '3'


volumes:
  bot_db:


services:

  database:
    image: postgres
    container_name: "bot_db"
    volumes:
      - bot_db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
